### ISSUE TITLE
授权登录后无法跳转

### ISSUE THREAD

**Issue by Angious** [YYJeffrey/july_client#6]
测试环境下，按照文档说明配置好，但授权登录后无法正常跳转至主页，报错信息：
MiniProgramError
wx.getUserProfile is not a function
TypeError: wx.getUserProfile is not a function
    at Ze.auth (http://127.0.0.1:30822/appservice/pages/auth/index.js:35:8)
    at Object.r.safeCallback (http://127.0.0.1:30822/appservice/__dev__/WAService.js?t=wechat&s=1637151909544&v=2.12.2:2:1954289)
    at http://127.0.0.1:30822/appservice/__dev__/WAService.js?t=wechat&s=1637151909544&v=2.12.2:2:2123485
    at s (http://127.0.0.1:30822/appservice/__dev__/WAService.js?t=wechat&s=1637151909544&v=2.12.2:2:2050351)
    at http://127.0.0.1:30822/appservice/__dev__/WAService.js?t=wechat&s=1637151909544&v=2.12.2:2:2123410
    at r (http://127.0.0.1:30822/appservice/__dev__/WAService.js?t=wechat&s=1637151909544&v=2.12.2:2:2031780)
    at http://127.0.0.1:30822/appservice/__dev__/WAService.js?t=wechat&s=1637151909544&v=2.12.2:2:2031902
    at http://127.0.0.1:30822/appservice/__dev__/WAService.js?t=wechat&s=1637151909544&v=2.12.2:2:959048
    at i (http://127.0.0.1:30822/appservice/__dev__/asdebug.js:1:73981)
    at c (http://127.0.0.1:30822/appservice/__dev__/asdebug.js:1:74092)(env: Windows,mp,1.05.2108130; lib: 2.12.2)
errorReport @ VM547 WAService.js:2
thirdErrorReport @ VM547 WAService.js:2
(anonymous) @ VM547 WAService.js:2
(anonymous) @ VM547 WAService.js:2
r.safeCallback @ VM547 WAService.js:2
r.call @ VM547 WAService.js:2
message @ VM547 WAService.js:2
r.safeCallback @ VM547 WAService.js:2
(anonymous) @ VM547 WAService.js:2
s @ VM547 WAService.js:2
(anonymous) @ VM547 WAService.js:2
r @ VM547 WAService.js:2
(anonymous) @ VM547 WAService.js:2
(anonymous) @ VM547 WAService.js:2
i @ VM8 asdebug.js:1
c @ VM8 asdebug.js:1
(anonymous) @ VM8 asdebug.js:1
f @ VM8 asdebug.js:1
g @ VM8 asdebug.js:1
(anonymous) @ VM8 asdebug.js:1
_ws.onmessage @ VM8 asdebug.js:1

**Comment by YYJeffrey** [comment]
确保注册时填写的是小程序的APPID，并且不是IP白名单模式
